version: "3.0"
services:
  project-zomboid:
    image: cyrale/project-zomboid
    container_name: project-zomboid
    ports:
      - "${PORT}:${PORT}/udp"
      - "${PORT2}:${PORT2}/udp"
    restart: unless-stopped
    volumes:
      - "${VOLUME}"
    stdin_open: true
    tty: true
    environment:
      SERVER_NAME: "${SERVER_NAME}"
      SERVER_PASSWORD: "${SERVER_PASSWORD}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"