version: "3"
services:
  plex: #default port is 32400
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - VERSION=docker
      #- PLEX_CLAIM= #optional
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${TVDIR}:/tv
      - ${MOVIEDIR}:/movies
    restart: unless-stopped

  tautulli: #default port is 8181
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/tautulli:/config
    restart: unless-stopped

  overseerr: #default port is 5055
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/overseerr:/config
    restart: unless-stopped

  prowlarr: #default port is 9696
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config
    restart: unless-stopped

  sonarr: #default port is 8989
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: host
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/sonarr:/config
      - ${TVDIR}:/tv #optional
      - ${DLDIR}:/downloads #optional
    restart: unless-stopped

  radarr: #default port is 7878
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: host
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/radarr:/config
      - ${MOVIEDIR}:/movies #optional
      - ${DLDIR}:/downloads #optional
    restart: unless-stopped

  qbittorrent: #default port is 8080
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: host
    environment:
      - PUID=3000
      - PGID=3000
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${CONFIG_DIR}/qbittorrent:/config
      - ${DLDIR}:/downloads
    restart: unless-stopped
