site_name: Smith Labs Docs

site_url: https://docs.smithhomelab.com

repo_name: lilthrasher/homelab-docker

repo_url: https://github.com/Lilthrasher/homelab-docker

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: slate
      primary: black
      accent: indigo
  # palette:
  #   - media: "(prefers-color-scheme)"
  #     toggle:
  #       icon: material/link
  #       name: Switch to light mode
  #   - media: "(prefers-color-scheme: light)"
  #     scheme: default
  #     primary: indigo
  #     accent: indigo
  #     toggle:
  #       icon: material/toggle-switch
  #       name: Switch to dark mode
  #   - media: "(prefers-color-scheme: dark)"
  #     scheme: slate
  #     primary: black
  #     accent: indigo
  #     toggle:
  #       icon: material/toggle-switch-off
  #       name: Switch to system preference

nav:
  - Smith Labs: index.md
  - Docker:
    - Installing Docker: docker/installation.md
    - Post Installation: docker/post-installation.md
    - Configuring Remote Access For Docker Daemon: docker/expose-api.md
  - Docker Compose:
    - Docker Compose Files: docker_compose/compose.md
    - Environment Files: docker_compose/environment.md
  - Containers:
    - Adguard: containers/adguard.md
    - Cloudflare DDNS: containers/cloudflare.md
    - Grafana: containers/grafana.md
    - Guacamole: containers/guacamole.md
    - Homepage: containers/homepage.md
    - Jellyfin: containers/jellyfin.md
    - Media Stack: containers/media.md
    - Netboot XYZ: containers/netboot.md
    - Nginx Proxy Manager: containers/npm.md
    - NTFY: containers/ntfy.md
    - Plex: containers/plex.md
    - Portainer: containers/portainer.md
    - Speed Test Tracker: containers/speedtest.md
    - Uptime Kuma: containers/uptime.md
    - Watchtower: containers/watchtower.md
  - Proxmox:
    - No Subscription Repository: proxmox/nosubrepo.md
    - Qemu Settings: proxmox/qemu_settings.md
    - Shared Storage: proxmox/shared_storage.md

plugins:
  - search
  - social

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra:
  analytics:
    provider: google
    property: G-41CKLY8X0G