version: "3"
services:
  speedtest-tracker:
    image: ghcr.io/alexjustesen/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: unless-stopped
    ports:
      - ${SPEED_PORT}:443
    volumes:
      - /etc/timezone:/etc/timezone
      - ${SPEED_DIR}:/config
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=speedtest_tracker
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - APP_KEY=base64:${APP_KEY}
    depends_on:
      - maria-db

  maria-db:
    image: mariadb:10
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=speedtest_tracker
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASS}
      - MARIADB_RANDOM_ROOT_PASSWORD=false
    volumes:
      - ${DB_DIR}:/var/lib/mysql