version: "3.3"
services:
  speedtest-tracker:
    image: ghcr.io/alexjustesen/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: on-failure:5
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - /etc/timezone:/etc/timezone
      - ./speedtest-data:/config