services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: unless-stopped
    ports:
      - ${SPEED_PORT}:443
    volumes:
      - /etc/timezone:/etc/timezone
      - ${SPEED_DIR}:/config
    environment:
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=sqlite
      - APP_KEY=base64:${APP_KEY}
      - DISPLAY_TIMEZONE=America/Indiana/Indianapolis
      - PRUNE_RESULTS_OLDER_THAN=30
      - SPEEDTEST_SCHEDULE=0 * * * *