services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    user: "${GRAFANA_UID}"
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - /etc/timezone:/etc/timezone
      - ${GRAFANA_DIR}:/var/lib/grafana
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
