services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - ${CLOUD_PORT}:443
    volumes:
      - /etc/timezone:/etc/timezone
      - ${CONFIG_DIR}:/config
      - ${DATA_DIR}:/data
    environment:
      - PUID=3000
      - PGID=3000