version: "3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - ${PAGE_PORT}:3000
    volumes:
      - /etc/timezone:/etc/timezone
      - ${DATA_DIR}:/app/config
      - ${SECRET_DIR}