version: "3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - $(PAGE-PORT):3000
    volumes:
      - /etc/timezone:/etc/timezone
      - $(DATA-DIR):/app/config
      - $(SECRET-DIR)