version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: on-failure:5
    volumes:
      - /etc/timezone:/etc/timezone
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP= true
      - WATCHTOWER_SCHEDULE= 0 0 0 * * *