services:
  nessus:
    image: tenableofficial/nessus
    container_name: nessus
    restart: unless-stopped
    ports:
      - ${NESSUS_PORT}:8834
    envirooonment:
      ACTIVATION_CODE: ${NESSUS_CODE}