services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_DIR}/jellyfin:/config
      - ${MOVIE_DIR}:/data/movies
      - ${TV_DIR}:/data/tvshows
    ports:
      - 8096:8096
    restart: unless-stopped