version: "3"
services:
  portainer-server:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: on-failure:5
    ports: 
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /etc/timezone:/etc/timezone
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - ./portainer-data:/data