version: "3"
services:
  gmod-ttt:
    image: hackebein/garrysmod
    container_name: garrysmod-ttt
    ports:
      - "${PORT}:${PORT}/tcp"
      - "${PORT}:${PORT}/udp"
    restart: "unless-stopped"
    volumes:
      - "/etc/timezone:/etc/timezone"
      - "${VOLUME}"
    stdin_open: true
    tty: true
    environment:
      PORT: "${PORT}"
      WORKSHOP: "${WORKSHOP}"
      WORKSHOPDL: "${WORKSHOP}"
      GAMEMODE: "${GAMEMODE}"
      MAP: "${START_MAP}"
      AUTHKEY: "${AUTHKEY}"
      CUSTOMPARAMETERS: ""