version: "3"
services:
  ghost:
    image: ghost
    container_name: ghost-blog
    restart: unless-stopped
    ports:
      - ${GHOST_PORT}:2368
    volumes:
      - /etc/timezone:/etc/timezone
      - ${GHOST_DIR}:/var/lib/ghost/content
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ghost
      url: ${GHOST_URL}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: ghost-mysql
    restart: unless-stopped
    volumes:
      - /etc/timezone:/etc/timezone
      - ${DB_DIR}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: mysqladmin --password=${DB_PASSWORD} version
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 5s