version: "3"
services:
  metube:
    image: alexta69/metube
    container_name: metube
    restart: on-failure:5
    ports:
      - "8081:8081"
    volumes:
      - /etc/timezone:/etc/timezone
      - ./downloads:/downloads