version: "3"
services:
  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - ${METUBE_PORT}:8081
    volumes:
      - 3301:/downloads
    environment:
      - YTDL_OPTIONS={"ignoreerrors":true}