version: "3"
services:
  metube:
    image: alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - $(METUBE-PORT):8081
    volumes:
      - $(METUBE-DIR):/downloads
    environment:
      - YTDL_OPTIONS={"ignoreerrors":true}