version: "3"
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: unless-stopped
    ports:
      - ${INFLUX_PORT}:8086
    volumes:
      - /etc/timezone:/etc/timezone
      - ${INFLUX_DIR}:/var/lib/influxdb2
      - ${INFLUX_DIR}:/etc/influxdb2