name: Redeploy Containers With Changes

on:
  push:
    paths:
      - '**/docker-compose.yaml' # Trigger the workflow on changes to YAML files
  workflow_dispatch:

jobs:
  Redeploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Identify changed Docker Compose files
      id: changed-files
      run: |
        CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.before }} ${{ github.sha }} | grep '\.yaml$' | grep -vE '\.github/workflows/.*\.yaml$' || true)
        CHANGED_FILES_CSV=$(echo "$CHANGED_FILES" | tr '\n' ',' | sed 's/,$//')
        echo "Changed files: $CHANGED_FILES_CSV"
        echo "::set-output name=files::$CHANGED_FILES_CSV"

    - name: Copy and deploy updated Docker Compose files
      run: |
        IFS=',' read -ra FILES <<< "${{ steps.changed-files.outputs.files }}"
        for file in "${FILES[@]}"; do
          echo "Copying $file to server..."
          cp -f "$file" /home/kyle/docker-files/"$file"
        done
        cd /home/kyle/docker-files

        IFS=',' read -ra FILES <<< "${{ steps.changed-files.outputs.files }}"
        for file in "${FILES[@]}"; do
          service_name=$(dirname "$file" | xargs basename)
          echo "Updating $file..."
          if DEPLOY_OUTPUT=$(docker compose -f "$file" up -d --force-recreate 2>&1); then
            curl -u ${{ secrets.NTFY_LOGIN }} -H "Title: Container Redeployed" -H "Tags: tada" -d "$service_name was redeployed successfully." ntfy.smithhomelab.com/Smith-Labs
          else
            curl -u ${{ secrets.NTFY_LOGIN }} -H "Title: Redeployment Failed" -H "Tags: skull" -d "$service_name encountered an error while redeploying. OUTPUT:$(echo "$DEPLOY_OUTPUT" | cut -d':' -f2- | sed 's/^[ \t]*//;s/[ \t]*$//')" ntfy.smithhomelab.com/Smith-Labs
          fi
        done