name: Test Containers With Changes

on:
  pull_request:
    paths:
      - '**/docker-compose.yaml' # Trigger the workflow on changes to YAML files
  workflow_dispatch:

jobs:
  Test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Identify Changed Docker Compose files
      id: changed-files
      run: |
        CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.before }} ${{ github.sha }} | grep '\.yaml$' | grep -vE '\.github/workflows/.*\.yaml$' || true)
        CHANGED_FILES_CSV=$(echo "$CHANGED_FILES" | tr '\n' ',' | sed 's/,$//')
        echo "Changed files: $CHANGED_FILES_CSV"
        echo "::set-output name=files::$CHANGED_FILES_CSV"

    - name: Copy and Test Updated Docker Compose files
      run: |
        mkdir temp
        IFS=',' read -ra FILES <<< "${{ steps.changed-files.outputs.files }}"
        for file in "${FILES[@]}"; do
          echo "Copying $file to temp..."
          cp -f "$file" temp/"$file"
        done
        cd temp/

        IFS=',' read -ra FILES <<< "${{ steps.changed-files.outputs.files }}"
        for file in "${FILES[@]}"; do
          service_name=$(dirname "$file" | xargs basename)
          echo "Testing $file..."
          if docker compose -f "$file" up -d --force-recreate; then
            curl -u ${{ secrets.NTFY_LOGIN }} -H "Title: Container Passed Tests" -H "Tags: tada" -d "$service_name is able to deploy." ntfy.smithhomelab.com/Smith-Labs
            docker compose down
          else
            curl -u ${{ secrets.NTFY_LOGIN }} -H "Title: Container Failed Tests" -H "Tags: skull" -d "$service_name is unable to deploy." ntfy.smithhomelab.com/Smith-Labs
          fi
        done
    
    - name: Test Cleanup
      run: |
        rm -rf temp
        echo "Temporary directory removed."