name: Deploy Docker Compose

on:
  push:
    paths:
      - '**/docker-compose.yaml' # Trigger the workflow on changes to YAML files

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Identify changed Docker Compose files
      id: changed-files
      run: |
        CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.yml$' || true)
        echo "::set-output name=files::$CHANGED_FILES"

    - name: Copy and deploy updated Docker Compose files
      run: |
        cp ${{ steps.changed-files.outputs.files }} /home/kyle/docker-files/

    - name: SSH into the server and redeploy services
      run: |
        cd /home/kyle/docker-files/
        for file in ${{ steps.changed-files.outputs.files }}; do
            filename=$(basename "$file")
            relative_path=$(dirname "$file")
            echo "Updating $relative_path/$filename..."
            docker-compose -f "$relative_path/$filename" up -d --force-recreate
        done

    - name: Send Push Notification on Fail
      if: failure()
      run: |
        curl -u ${{ secrets.NTFY_LOGIN }} -H "Title: Deployment Failed" -H "Tags: skull" -d "Container Deployment Failed." ntfy.smithhomelab.com/Smith-Labs

    - name: Send Push Notification on Success
      if: success()
      run: |
        curl -u ${{ secrets.NTFY_LOGIN }} -H "Title: Container Redeployed" -H "Tags: tada" -d "Container Successfully Redeployed." ntfy.smithhomelab.com/Smith-Labs