name: Deploy Docker Compose

on:
  push:
    paths:
      - '**/docker-compose.yaml' # Trigger the workflow on changes to YAML files

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Identify changed Docker Compose files
      id: changed-files
      run: |
        CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.event.before }} ${{ github.sha }} | grep '\.yaml$' | grep -vE '\.github/workflows/.*\.yaml$' || true)
        CHANGED_FILES_CSV=$(echo "$CHANGED_FILES" | tr '\n' ',' | sed 's/,$//')
        echo "Changed files: $CHANGED_FILES_CSV"
        echo "::set-output name=files::$CHANGED_FILES_CSV"

    - name: Copy and deploy updated Docker Compose files
      run: |
        IFS=',' read -ra FILES <<< "${{ steps.changed-files.outputs.files }}"
        for file in "${FILES[@]}"; do
          echo "Copying $file to server..."
          cp -f "$file" /home/kyle/docker-files/"$file"
        done
        cd /home/kyle/docker-files

        IFS=',' read -ra FILES <<< "${{ steps.changed-files.outputs.files }}"
        #for file in "${FILES[@]}"; do
          echo "Updating $file..."
          docker compose -f "$file" up -d --force-recreate
        done

    - name: Send Push Notification on Fail
      if: failure()
      run: |
        curl -u ${{ secrets.NTFY_LOGIN }} -H "Title: Deployment Failed" -H "Tags: skull" -d "Container Deployment Failed." ntfy.smithhomelab.com/Smith-Labs

    - name: Send Push Notification on Success
      if: success()
      run: |
        curl -u ${{ secrets.NTFY_LOGIN }} -H "Title: Container Redeployed" -H "Tags: tada" -d "Container Successfully Redeployed." ntfy.smithhomelab.com/Smith-Labs