services:
  trudesk:
    image: polonel/trudesk:1
    container_name: trudesk
    restart: unless-stopped
    ports:
      - "${TRUDESK_PORT}:8118"
    environment:
      NODE_ENV: production
      TRUDESK_DOCKER: "true"
      TD_MONGODB_SERVER: mongo
      TD_MONGODB_DATABASE: trudesk
      USE_XFORWARDIP: "true"
    volumes:
      - ${TRUDESK_DIR}/trudesk_uploads:/usr/src/trudesk/public/uploads
      - ${TRUDESK_DIR}/trudesk_backups:/usr/src/trudesk/backups
  mongo:
    image: mongo:5.0-focal
    container_name: trudesk-mongodb
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ${MONGO_DIR}/mongo:/var/lib/mongo
      - ${MONGO_DIR}/mongo_data:/data/db:rw
  elasticsearch:
    image: elasticsearch:8.0.0
    container_name: trudesk-elastic
    restart: unless-stopped
    environment:
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${SEARCH_PORT}:9200"
      - "${SEARCH_PORT_2}:9300"
    volumes:
      - ${SEARCH_DIR}/elasticsearch:/usr/share/elasticsearch/data